---
title: "simulations"
output: github_document
date: "2022-11-06"
---

```{r, include=FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


# Simulations

Here is the function from before

```{r}
sim_mean_sd = function(n_obs, mu = 7, sigma = 4){
  
  x = rnorm(n=n_obs,mean = mu, sd = sigma)

  
tibble(
    mu_hat = mean(x),
    sigma_hat = sd(x)
  )
}
```

How did we use it before?

```{r}
sim_mean_sd(n_obs = 30)
```

How can we use this now

let's start with a loop!

```{r}
output = vector("list", length = 100)

for (i in 1:100){
  output[[i]] = sim_mean_sd(30)
}

bind_rows(output) %>% 
  view
```

let's use list columns instead.

```{r}
sim_results_df = 
  expand_grid(
    sample_size = 30,
    iteration = 1:100) %>%
  mutate(
    estimate_df = map(sample_size, sim_mean_sd)
  ) %>%
  unnest(estimate_df)
```

```{r}
sim_results_df %>%
  ggplot(aes(x= mu_hat))+ 
  geom_density()
```

!!!!!!!!!!!!!