---
title: "writing_functions"
output: github_document
date: "2022-11-05"
---

```{r, include=FALSE}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## Z scores!!

Let's compute the z-scores version of a list of numbers.

```{r}
x_vec = rnorm(25,mean =7,sd=4)

(x_vec-mean(x_vec))/(sd(x_vec))
```

Suppose you want to do this often.

```{r}
z_scores = function(x){
  
  if(!is.numeric(x)){
    stop("Z scores only work for numbers")
  }
  
  if(length(x)<3){
    stop("Z scores really only work if you have thee or more numbers")
  }
  
  z = (x-mean(x))/(sd(x))
  
  z
}
```

```{r}
z_scores(x_vec)

z_scores(x=1:10)
z_scores(x=rbinom(1000,1,.6))

#z_scores(x=3)
#z_scores("my name is Wenjing Yang")
```

## let's have multiple outputs

let's just get the mean and sd from the vector output.

```{r}
mean_and_sd = function(x){

  if(!is.numeric(x)){
    stop("Z scores only work for numbers")
  }
  
  if(length(x)<3){
    stop("Z scores really only work if you have thee or more numbers")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(
    mean = mean_x,
    sd = sd_x
  )
}
```

```{r}
mean_and_sd(x_vec)
mean_and_sd(1:10)
mean_and_sd(rbinom(1000,1,.5))
```

## let's start with simulation...

```{r}
x_vec = rnorm(25,mean =7,sd=4)

  
tibble(
    mean = mean(x_vec),
    sd = sd(x_vec)
  )
```

Can I do this using function? Yup

```{r}
sim_mean_sd = function(n_obs, true_mean = 7, true_sd = 4){
  
  x = rnorm(n=n_obs,mean =true_mean,sd=true_sd)

  
tibble(
    mean = mean(x),
    sd = sd(x)
  )
}
```

Does it work?

```{r}
sim_mean_sd(2500,10,3)
```

## Fixing bad stuff

```{r}
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

dynamite_html = read_html(url)

review_titles = 
  dynamite_html %>%
  html_nodes(".a-text-bold span") %>%
  html_text()

review_stars = 
  dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-rating") %>%
  html_text() %>%
  str_extract("^\\d") %>%
  as.numeric()

review_text = 
  dynamite_html %>%
  html_nodes(".review-text-content span") %>%
  html_text() %>% 
  str_replace_all("\n", "") %>% 
  str_trim()

reviews = tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
)
```

